version: "1.0"
info:
  model: int-scaffold
packages:
- name: GP01_Super_iPaaSProject
  gitServerName: kalpshekhar-sag
  gitUrl: https://github.com/SoftwareAG/GP01_Super_iPaaSProject
  gitUsername: kalpshekhar-sag
  gitBranch: main
services:
- serviceName: project.gp01_super_ipaas.integrations:generateQuotation
  packages:
  - name: GP01_Super_iPaaSProject
    version: "1.0"
- serviceName: pub.string:isNumber
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: pub.math:multiplyFloats
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: pub.math:subtractFloats
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: project.gp01_super_ipaas.integrations:getCustomerById
  packages:
  - name: GP01_Super_iPaaSProject
    version: "1.0"
